"use client";

import { useMemo, useState } from "react";
import type { AdminNavItem } from "@/admin/types";
import { SafeImage } from "@/components/ui/SafeImage";
import { registerExternalAsset, uploadAsset } from "@/content/cms-store";
import type { AssetRecord, PortfolioSnapshot, RevisionRecord } from "@/content/schema";
import type { ObjectPosition } from "@/types/content";
import { AssetPicker } from "./AssetPicker";
import { WorksReorder } from "./WorksReorder";
import styles from "./admin.module.css";

type Props = { selectedItem: AdminNavItem; content: PortfolioSnapshot; onChange: (content: PortfolioSnapshot) => void; revisions: RevisionRecord[]; onRestore: (revision: RevisionRecord) => void; onProjectSelect?: (slug: string) => void };
type SectionKey = "projects" | "works" | "career" | "workflow" | "contact";
const positions: ObjectPosition[] = ["top-left", "top", "top-right", "left", "center", "right", "bottom-left", "bottom", "bottom-right"];

function Field({ label, help, children }: { label: string; help?: string; children: React.ReactNode }) {
  return <label className={styles.field}><span>{label}</span>{children}{help ? <small>{help}</small> : null}</label>;
}
function FieldGroup({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) {
  return <section className={styles.fieldGroup}><header><h3>{title}</h3>{description ? <p>{description}</p> : null}</header><div>{children}</div></section>;
}
function move<T>(items: T[], index: number, offset: -1 | 1) { const next = [...items]; const target = index + offset; if (target < 0 || target >= next.length) return next; [next[index], next[target]] = [next[target], next[index]]; return next; }

function SectionCopyEditor({ section, onPatch }: { section: { eyebrow: string; title: string; description: string }; onPatch: (patch: Partial<typeof section>) => void }) {
  return <><Field label="Eyebrow"><input required value={section.eyebrow} onChange={(event) => onPatch({ eyebrow: event.target.value })} /></Field><Field label="Title"><textarea required rows={3} value={section.title} onChange={(event) => onPatch({ title: event.target.value })} /></Field><Field label="Description"><textarea required rows={5} value={section.description} onChange={(event) => onPatch({ description: event.target.value })} /></Field></>;
}

function OrderedRows({ items, label, onMove, onSelect, selectedIndex }: { items: { id: string; title?: string; company?: string; visible: boolean }[]; label: string; onMove: (index: number, offset: -1 | 1) => void; onSelect: (index: number) => void; selectedIndex?: number }) {
  return <section className={styles.editorBlock}><div className={styles.blockHeading}><div><p className={styles.kicker}>Ordered entries</p><h3>{label}</h3></div><span className={styles.count}>{items.length}</span></div>{items.map((item, index) => <div className={`${styles.compactRow} ${selectedIndex === index ? styles.compactRowSelected : ""}`} key={item.id}><span className={styles.dragHandle}>⠿</span><span>{String(index + 1).padStart(2, "0")}</span><strong>{item.title ?? item.company}</strong><button type="button" onClick={() => onMove(index, -1)} disabled={!index}>↑</button><button type="button" onClick={() => onMove(index, 1)} disabled={index === items.length - 1}>↓</button><button type="button" onClick={() => onSelect(index)} aria-pressed={selectedIndex === index}>Edit</button></div>)}</section>;
}

export function PropertyEditor({ selectedItem, content, onChange, revisions, onRestore, onProjectSelect }: Props) {
  const [pickerOpen, setPickerOpen] = useState(false);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [subIndex, setSubIndex] = useState(0);
  const [galleryIndex, setGalleryIndex] = useState(0);
  const [workQuery, setWorkQuery] = useState("");
  const [workCategory, setWorkCategory] = useState("All");
  const [workVisibility, setWorkVisibility] = useState<"all" | "published" | "hidden" | "home" | "featured">("all");
  const [assetTarget, setAssetTarget] = useState<"work" | "project-thumbnail" | "project-gallery" | "library">("library");
  const updateHome = <K extends keyof PortfolioSnapshot["home"]>(key: K, value: PortfolioSnapshot["home"][K]) => onChange({ ...content, home: { ...content.home, [key]: value } });
  const patchSection = (key: SectionKey, patch: Partial<PortfolioSnapshot["home"][SectionKey]>) => updateHome(key, { ...content.home[key], ...patch });
  const hero = content.home.hero;
  const about = content.home.about;
  const selectedWork = content.works[Math.min(selectedIndex, content.works.length - 1)];
  const selectedProject = content.projects[Math.min(selectedIndex, content.projects.length - 1)];
  const filteredWorks = useMemo(() => content.works.map((work, index) => ({ work, index })).filter(({ work }) => {
    const matchesState = workVisibility === "all"
      || (workVisibility === "published" && work.published)
      || (workVisibility === "hidden" && !work.published)
      || (workVisibility === "home" && work.showOnHome)
      || (workVisibility === "featured" && work.homeFeatured);
    return matchesState && (workCategory === "All" || work.category === workCategory) && `${work.title} ${work.description ?? ""}`.toLocaleLowerCase().includes(workQuery.trim().toLocaleLowerCase());
  }), [content.works, workCategory, workQuery, workVisibility]);

  const mergedAssets = (asset: AssetRecord) => [...content.assets.filter((item) => item.id !== asset.id), asset];
  const updateSelectedProject = (patch: Partial<NonNullable<typeof selectedProject>>) => {
    if (!selectedProject) return;
    onChange({ ...content, projects: content.projects.map((item) => item.slug === selectedProject.slug ? { ...item, ...patch } : item) });
  };
  const reorderProjects = (index: number, offset: -1 | 1) => {
    const reordered = move(content.projects, index, offset).map((project, order) => ({ ...project, sortOrder: order + 1 }));
    onChange({ ...content, projects: reordered });
    setSelectedIndex(Math.max(0, Math.min(content.projects.length - 1, index + offset)));
    onProjectSelect?.(reordered[Math.max(0, Math.min(content.projects.length - 1, index + offset))]?.slug ?? "livbee");
  };
  const chooseAsset = (asset: AssetRecord) => {
    const assets = mergedAssets(asset);
    if (assetTarget === "work" && selectedWork) onChange({ ...content, assets, works: content.works.map((item) => item.id === selectedWork.id ? { ...item, src: asset.src, alt: asset.alt || item.alt, focus: asset.objectPosition } : item) });
    else if (assetTarget === "project-thumbnail" && selectedProject) onChange({ ...content, assets, projects: content.projects.map((item) => item.id === selectedProject.id ? { ...item, thumbnail: { ...item.thumbnail, src: asset.src, alt: asset.alt || item.thumbnail.alt, focus: asset.objectPosition } } : item) });
    else if (assetTarget === "project-gallery" && selectedProject) onChange({ ...content, assets, projects: content.projects.map((item) => item.slug === selectedProject.slug ? { ...item, gallery: item.gallery.map((media, index) => index === galleryIndex ? { ...media, src: asset.src, alt: asset.alt || media.alt, focus: asset.objectPosition } : media) } : item) });
    else onChange({ ...content, assets });
    setPickerOpen(false);
  };

  return <section className={styles.propertyPane} aria-labelledby="property-heading">
    <header className={styles.propertyHeader}><p className={styles.breadcrumb}>Portfolio / {selectedItem.id.startsWith("home.") ? "Home / " : ""}{selectedItem.label}</p><h2 id="property-heading">{selectedItem.label}</h2><p>입력값은 오른쪽 실제 Portfolio Preview에 즉시 반영됩니다.</p></header>
    <div className={styles.propertyScroll}><div className={styles.editorForm}>
      {selectedItem.id === "home.hero" ? <>
        <SectionCopyEditor section={hero} onPatch={(patch) => updateHome("hero", { ...hero, ...patch })} />
        <fieldset className={styles.fieldset}><legend>Line break policy</legend><div className={styles.radioGroup}><label><input type="radio" checked={hero.lineBreaks === "auto"} onChange={() => updateHome("hero", { ...hero, lineBreaks: "auto" })} /> 자동</label><label><input type="radio" checked={hero.lineBreaks === "manual"} onChange={() => updateHome("hero", { ...hero, lineBreaks: "manual" })} /> 입력 줄바꿈 유지</label></div></fieldset>
        <div className={styles.twoFields}><Field label="Period"><input required value={hero.period} onChange={(event) => updateHome("hero", { ...hero, period: event.target.value })} /></Field><Field label="Disciplines"><input required value={hero.disciplines} onChange={(event) => updateHome("hero", { ...hero, disciplines: event.target.value })} /></Field></div>
      </> : null}

      {selectedItem.id === "home.about" ? <>
        <SectionCopyEditor section={about} onPatch={(patch) => updateHome("about", { ...about, ...patch })} />
        <OrderedRows items={about.capabilities} label="Experience areas" onMove={(index, offset) => updateHome("about", { ...about, capabilities: move(about.capabilities, index, offset) })} onSelect={setSelectedIndex} selectedIndex={selectedIndex} />
        {about.capabilities[selectedIndex] ? <><Field label="Capability title"><input value={about.capabilities[selectedIndex].title} onChange={(event) => updateHome("about", { ...about, capabilities: about.capabilities.map((item, index) => index === selectedIndex ? { ...item, title: event.target.value } : item) })} /></Field><Field label="Capability description"><input value={about.capabilities[selectedIndex].description} onChange={(event) => updateHome("about", { ...about, capabilities: about.capabilities.map((item, index) => index === selectedIndex ? { ...item, description: event.target.value } : item) })} /></Field><label><input type="checkbox" checked={about.capabilities[selectedIndex].visible} onChange={(event) => updateHome("about", { ...about, capabilities: about.capabilities.map((item, index) => index === selectedIndex ? { ...item, visible: event.target.checked } : item) })} /> Visible</label></> : null}
      </> : null}

      {(["home.projects", "home.works", "home.career", "home.workflow", "home.contact"] as string[]).includes(selectedItem.id) ? <SectionCopyEditor section={content.home[selectedItem.id.split(".")[1] as SectionKey]} onPatch={(patch) => patchSection(selectedItem.id.split(".")[1] as SectionKey, patch)} /> : null}

      {selectedItem.id === "home.projects" ? <OrderedRows items={content.projects.map((item) => ({ id: item.id, title: item.title, visible: item.visible }))} label="Projects" onMove={reorderProjects} onSelect={(index) => { setSelectedIndex(index); onProjectSelect?.(content.projects[index]?.slug ?? "livbee"); }} selectedIndex={selectedIndex} /> : null}
      {selectedItem.id === "home.works" ? <WorksReorder items={content.works} onChange={(works) => onChange({ ...content, works })} /> : null}
      {selectedItem.id === "home.career" ? <><OrderedRows items={content.career} label="Career" onMove={(index, offset) => onChange({ ...content, career: move(content.career, index, offset) })} onSelect={setSelectedIndex} />{content.career[selectedIndex] ? <><Field label="Period"><input value={content.career[selectedIndex].period} onChange={(event) => onChange({ ...content, career: content.career.map((item, index) => index === selectedIndex ? { ...item, period: event.target.value } : item) })} /></Field><Field label="Company"><input value={content.career[selectedIndex].company} onChange={(event) => onChange({ ...content, career: content.career.map((item, index) => index === selectedIndex ? { ...item, company: event.target.value } : item) })} /></Field><Field label="Team"><input value={content.career[selectedIndex].team} onChange={(event) => onChange({ ...content, career: content.career.map((item, index) => index === selectedIndex ? { ...item, team: event.target.value } : item) })} /></Field><Field label="Role"><input value={content.career[selectedIndex].role} onChange={(event) => onChange({ ...content, career: content.career.map((item, index) => index === selectedIndex ? { ...item, role: event.target.value } : item) })} /></Field><Field label="Description"><textarea rows={4} value={content.career[selectedIndex].description} onChange={(event) => onChange({ ...content, career: content.career.map((item, index) => index === selectedIndex ? { ...item, description: event.target.value } : item) })} /></Field></> : null}</> : null}
      {selectedItem.id === "home.workflow" ? <><OrderedRows items={content.workflow} label="Workflow" onMove={(index, offset) => onChange({ ...content, workflow: move(content.workflow, index, offset) })} onSelect={setSelectedIndex} />{content.workflow[selectedIndex] ? <><Field label="Title"><input value={content.workflow[selectedIndex].title} onChange={(event) => onChange({ ...content, workflow: content.workflow.map((item, index) => index === selectedIndex ? { ...item, title: event.target.value } : item) })} /></Field><Field label="Description"><textarea rows={4} value={content.workflow[selectedIndex].description} onChange={(event) => onChange({ ...content, workflow: content.workflow.map((item, index) => index === selectedIndex ? { ...item, description: event.target.value } : item) })} /></Field><Field label="Tools (comma separated)"><input value={content.workflow[selectedIndex].tools.join(", ")} onChange={(event) => onChange({ ...content, workflow: content.workflow.map((item, index) => index === selectedIndex ? { ...item, tools: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) } : item) })} /></Field></> : null}</> : null}
      {selectedItem.id === "home.contact" ? <><Field label="CTA label"><input value={content.home.contact.ctaLabel} onChange={(event) => updateHome("contact", { ...content.home.contact, ctaLabel: event.target.value })} /></Field><Field label="CTA URL"><input required value={content.home.contact.ctaUrl} onChange={(event) => updateHome("contact", { ...content.home.contact, ctaUrl: event.target.value })} /></Field><Field label="Public email"><input type="email" value={content.home.contact.email} onChange={(event) => updateHome("contact", { ...content.home.contact, email: event.target.value })} /></Field><Field label="Resume URL"><input type="url" value={content.home.contact.resumeUrl} onChange={(event) => updateHome("contact", { ...content.home.contact, resumeUrl: event.target.value })} /></Field></> : null}

      {selectedItem.id === "works.archive" ? <>
        <section className={styles.editorBlock}><div className={styles.blockHeading}><div><p className={styles.kicker}>Fixed taxonomy</p><h3>Categories</h3></div></div>{content.categories.map((category, index) => <div className={styles.compactRow} key={category.id}><span>{String(index + 1).padStart(2, "0")}</span><input value={category.label} onChange={(event) => onChange({ ...content, categories: content.categories.map((item) => item.id === category.id ? { ...item, label: event.target.value } : item), works: content.works.map((work) => work.category === category.label ? { ...work, category: event.target.value } : work) })} /><label><input type="checkbox" checked={category.visible} onChange={(event) => onChange({ ...content, categories: content.categories.map((item) => item.id === category.id ? { ...item, visible: event.target.checked } : item) })} /> visible</label><button type="button" aria-label={`${category.label} 위로 이동`} disabled={!index} onClick={() => onChange({ ...content, categories: move(content.categories, index, -1) })}>↑</button><button type="button" aria-label={`${category.label} 아래로 이동`} disabled={index === content.categories.length - 1} onClick={() => onChange({ ...content, categories: move(content.categories, index, 1) })}>↓</button></div>)}</section>
        <div className={styles.workFilters}><Field label="Search"><input type="search" value={workQuery} placeholder="제목 또는 설명" onChange={(event) => setWorkQuery(event.target.value)} /></Field><Field label="Category"><select value={workCategory} onChange={(event) => setWorkCategory(event.target.value)}><option>All</option>{content.categories.map((category) => <option key={category.id}>{category.label}</option>)}</select></Field><Field label="Exposure"><select value={workVisibility} onChange={(event) => setWorkVisibility(event.target.value as typeof workVisibility)}><option value="all">전체</option><option value="published">Published</option><option value="hidden">Hidden</option><option value="home">Home Reel</option><option value="featured">Featured</option></select></Field></div>
        <section className={styles.editorBlock}><div className={styles.blockHeading}><div><p className={styles.kicker}>Filtered entries</p><h3>Works</h3></div><span className={styles.count}>{filteredWorks.length}</span></div>{filteredWorks.map(({ work, index }) => <button className={`${styles.workResult} ${selectedIndex === index ? styles.workResultSelected : ""}`} type="button" key={work.id} onClick={() => setSelectedIndex(index)} aria-pressed={selectedIndex === index}><span>{work.category}</span><strong>{work.title}</strong><small>{work.published ? "Published" : "Draft"}</small></button>)}</section>
        {selectedWork ? <><Field label="Title"><textarea rows={2} required value={selectedWork.title} onChange={(event) => onChange({ ...content, works: content.works.map((item) => item.id === selectedWork.id ? { ...item, title: event.target.value } : item) })} /></Field><Field label="Category"><select value={selectedWork.category} onChange={(event) => onChange({ ...content, works: content.works.map((item) => item.id === selectedWork.id ? { ...item, category: event.target.value } : item) })}>{content.categories.map((category) => <option key={category.id}>{category.label}</option>)}</select></Field><Field label="Description"><textarea rows={3} value={selectedWork.description ?? ""} onChange={(event) => onChange({ ...content, works: content.works.map((item) => item.id === selectedWork.id ? { ...item, description: event.target.value } : item) })} /></Field><div className={styles.toggleGroup}><label><input type="checkbox" checked={selectedWork.published} onChange={(event) => onChange({ ...content, works: content.works.map((item) => item.id === selectedWork.id ? { ...item, published: event.target.checked } : item) })} /> Published</label><label><input type="checkbox" checked={selectedWork.showOnHome} disabled={selectedWork.homeFeatured} onChange={(event) => onChange({ ...content, works: content.works.map((item) => item.id === selectedWork.id ? { ...item, showOnHome: event.target.checked } : item) })} /> Home Reel</label><label><input type="radio" name="work-editor-featured" checked={selectedWork.homeFeatured} onChange={() => onChange({ ...content, works: content.works.map((item) => ({ ...item, showOnHome: item.id === selectedWork.id ? true : item.showOnHome, homeFeatured: item.id === selectedWork.id })) })} /> Home Featured</label></div></> : null}
        {selectedWork ? <section className={styles.imageProperty}><div className={styles.blockHeading}><div><p className={styles.kicker}>Image</p><h3>Replace & focal point</h3></div><button className={styles.textButton} type="button" onClick={() => { setAssetTarget("work"); setPickerOpen(true); }}>Replace</button></div><div className={styles.imagePreview}><SafeImage src={selectedWork.src} alt="" fill sizes="300px" style={{ objectFit: "cover" }} /></div><Field label="Alt"><textarea required rows={3} value={selectedWork.alt} onChange={(event) => onChange({ ...content, works: content.works.map((item) => item.id === selectedWork.id ? { ...item, alt: event.target.value } : item) })} /></Field><Field label="Caption"><input value={selectedWork.caption ?? ""} onChange={(event) => onChange({ ...content, works: content.works.map((item) => item.id === selectedWork.id ? { ...item, caption: event.target.value } : item) })} /></Field><fieldset className={styles.fieldset}><legend>Object position</legend><div className={styles.positionPicker}>{positions.map((position) => <button key={position} className={(selectedWork.focus ?? "center") === position ? styles.positionActive : ""} type="button" aria-label={position} onClick={() => onChange({ ...content, works: content.works.map((item) => item.id === selectedWork.id ? { ...item, focus: position } : item) })} />)}</div></fieldset></section> : null}
      </> : null}

      {selectedItem.id === "projects.index" ? <>
        <OrderedRows items={content.projects.map((item) => ({ id: item.id, title: item.title, visible: item.visible }))} label="Projects" onMove={reorderProjects} onSelect={(index) => { setSelectedIndex(index); setSubIndex(0); setGalleryIndex(0); onProjectSelect?.(content.projects[index]?.slug ?? "livbee"); }} selectedIndex={selectedIndex} />
        {selectedProject ? <>
          <div className={styles.selectedProjectHeading}><p className={styles.kicker}>Editing project {String(selectedIndex + 1).padStart(2, "0")}</p><h3>{selectedProject.title}</h3><p>{selectedProject.category}</p></div>
          <FieldGroup title="Basic" description="카드와 상세 페이지에서 공통으로 사용하는 기본 정보입니다.">
          <Field label="Category"><input required value={selectedProject.category} onChange={(event) => updateSelectedProject({ category: event.target.value, type: event.target.value })} /></Field>
          <Field label="Title"><input required value={selectedProject.title} onChange={(event) => updateSelectedProject({ title: event.target.value })} /></Field>
          <Field label="Subtitle"><textarea rows={3} value={selectedProject.subtitle} onChange={(event) => updateSelectedProject({ subtitle: event.target.value })} /></Field>
          <Field label="Summary"><textarea rows={4} value={selectedProject.summary} onChange={(event) => updateSelectedProject({ summary: event.target.value })} /></Field>
          <Field label="Roles (comma separated)"><input value={selectedProject.roles.join(", ")} onChange={(event) => updateSelectedProject({ roles: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} /></Field>
          <Field label="Tools (comma separated)"><input value={selectedProject.tools.join(", ")} onChange={(event) => updateSelectedProject({ tools: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} /></Field>
          </FieldGroup>
          <FieldGroup title="Thumbnail" description="Home 카드의 16:9 프레임과 상세 페이지에 함께 반영됩니다.">
          <section className={styles.imageProperty}><div className={styles.blockHeading}><div><p className={styles.kicker}>Project thumbnail</p><h3>{selectedProject.thumbnail.caption}</h3></div><button className={styles.textButton} type="button" onClick={() => { setAssetTarget("project-thumbnail"); setPickerOpen(true); }}>Replace</button></div><div className={styles.imagePreview}>{selectedProject.thumbnail.src ? <SafeImage src={selectedProject.thumbnail.src} alt="" fill sizes="300px" style={{ objectFit: "cover" }} /> : <span className={styles.emptyImage}>대표 이미지 미등록 · Replace에서 추가</span>}</div><Field label="Thumbnail alt"><textarea required rows={3} value={selectedProject.thumbnail.alt} onChange={(event) => updateSelectedProject({ thumbnail: { ...selectedProject.thumbnail, alt: event.target.value } })} /></Field><Field label="Thumbnail caption"><input value={selectedProject.thumbnail.caption} onChange={(event) => updateSelectedProject({ thumbnail: { ...selectedProject.thumbnail, caption: event.target.value } })} /></Field><fieldset className={styles.fieldset}><legend>Object position</legend><div className={styles.positionPicker}>{positions.map((position) => <button key={position} className={(selectedProject.thumbnail.focus ?? "center") === position ? styles.positionActive : ""} type="button" aria-label={position} onClick={() => updateSelectedProject({ thumbnail: { ...selectedProject.thumbnail, focus: position } })} />)}</div></fieldset></section>
          </FieldGroup>
          <FieldGroup title="Detail Content" description="상세 페이지의 도입부와 콘텐츠 섹션입니다.">
          <Field label="Intro"><textarea rows={4} value={selectedProject.intro} onChange={(event) => updateSelectedProject({ intro: event.target.value })} /></Field>
          <OrderedRows items={selectedProject.sections.map((section, index) => ({ id: `${selectedProject.slug}-section-${index}`, title: section.title, visible: true }))} label="Detail sections" onMove={(index, offset) => updateSelectedProject({ sections: move(selectedProject.sections, index, offset) })} onSelect={setSubIndex} />
          {selectedProject.sections[subIndex] ? <><Field label="Section label"><input value={selectedProject.sections[subIndex].label} onChange={(event) => updateSelectedProject({ sections: selectedProject.sections.map((section, index) => index === subIndex ? { ...section, label: event.target.value } : section) })} /></Field><Field label="Section title"><textarea rows={2} value={selectedProject.sections[subIndex].title} onChange={(event) => updateSelectedProject({ sections: selectedProject.sections.map((section, index) => index === subIndex ? { ...section, title: event.target.value } : section) })} /></Field><Field label="Section body"><textarea rows={4} value={selectedProject.sections[subIndex].body} onChange={(event) => updateSelectedProject({ sections: selectedProject.sections.map((section, index) => index === subIndex ? { ...section, body: event.target.value } : section) })} /></Field><Field label="Section items (comma separated)"><input value={(selectedProject.sections[subIndex].items ?? []).join(", ")} onChange={(event) => updateSelectedProject({ sections: selectedProject.sections.map((section, index) => index === subIndex ? { ...section, items: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) } : section) })} /></Field></> : null}
          </FieldGroup>
          <FieldGroup title="Gallery" description="상세 페이지에 노출되는 이미지와 캡션입니다.">
          <OrderedRows items={selectedProject.gallery.map((media, index) => ({ id: `${selectedProject.slug}-gallery-${index}`, title: media.caption, visible: true }))} label="Gallery" onMove={(index, offset) => updateSelectedProject({ gallery: move(selectedProject.gallery, index, offset) })} onSelect={setGalleryIndex} />
          {selectedProject.gallery[galleryIndex] ? <section className={styles.imageProperty}><div className={styles.blockHeading}><div><p className={styles.kicker}>Gallery image</p><h3>{selectedProject.gallery[galleryIndex].caption}</h3></div><button className={styles.textButton} type="button" onClick={() => { setAssetTarget("project-gallery"); setPickerOpen(true); }}>Replace</button></div><div className={styles.imagePreview}><SafeImage src={selectedProject.gallery[galleryIndex].src ?? ""} alt="" fill sizes="300px" style={{ objectFit: "cover" }} /></div><Field label="Gallery alt"><textarea required rows={3} value={selectedProject.gallery[galleryIndex].alt} onChange={(event) => updateSelectedProject({ gallery: selectedProject.gallery.map((media, index) => index === galleryIndex ? { ...media, alt: event.target.value } : media) })} /></Field><Field label="Gallery caption"><input value={selectedProject.gallery[galleryIndex].caption} onChange={(event) => updateSelectedProject({ gallery: selectedProject.gallery.map((media, index) => index === galleryIndex ? { ...media, caption: event.target.value } : media) })} /></Field><fieldset className={styles.fieldset}><legend>Object position</legend><div className={styles.positionPicker}>{positions.map((position) => <button key={position} className={(selectedProject.gallery[galleryIndex].focus ?? "center") === position ? styles.positionActive : ""} type="button" aria-label={position} onClick={() => updateSelectedProject({ gallery: selectedProject.gallery.map((media, index) => index === galleryIndex ? { ...media, focus: position } : media) })} />)}</div></fieldset></section> : null}
          </FieldGroup>
          <FieldGroup title="Links & Visibility" description="링크와 Public 노출 상태를 관리합니다.">
          <Field label="Detail page URL"><input required value={selectedProject.detailPageUrl} onChange={(event) => updateSelectedProject({ detailPageUrl: event.target.value })} /></Field>
          <Field label="External URL"><input type="url" value={selectedProject.externalUrl ?? ""} onChange={(event) => updateSelectedProject({ externalUrl: event.target.value || undefined })} /></Field>
          <div className={styles.toggleGroup}><label><input type="checkbox" checked={selectedProject.showOnHome} onChange={(event) => updateSelectedProject({ showOnHome: event.target.checked })} /> Show on Home</label><label><input type="checkbox" checked={selectedProject.visible} onChange={(event) => updateSelectedProject({ visible: event.target.checked })} /> Visible</label></div>
          <details className={styles.systemData}><summary>System data</summary><div className={styles.twoFields}><Field label="Project ID"><input value={selectedProject.id} readOnly /></Field><Field label="Slug"><input value={selectedProject.slug} readOnly /></Field></div></details>
          </FieldGroup>
        </> : null}
      </> : null}

      {selectedItem.id === "assets.library" ? <><section className={styles.editorBlock}><div className={styles.blockHeading}><div><p className={styles.kicker}>{content.assets.length} files</p><h3>Asset Library</h3></div><button className={styles.secondaryButton} type="button" onClick={() => { setAssetTarget("library"); setPickerOpen(true); }}>Add image</button></div><div className={styles.libraryList}>{content.assets.map((asset) => <article key={asset.id}><div className={styles.libraryThumb}><SafeImage src={asset.src} alt="" fill sizes="72px" style={{ objectFit: "cover" }} /></div><div><h4>{asset.filename}</h4><p>{asset.category} · {asset.source}</p><span>{asset.alt || "Alt text 필요"}</span></div></article>)}</div></section><section className={styles.editorBlock}><div className={styles.blockHeading}><div><p className={styles.kicker}>Recovery</p><h3>Published revisions</h3></div></div>{revisions.map((revision) => <div className={styles.revisionRow} key={revision.id}><span>v{revision.versionNumber}</span><strong>{new Date(revision.publishedAt).toLocaleString("ko-KR")}</strong><p>{revision.snapshot.home.hero.title.replace(/\n/g, " ")}{revision.note ? ` · ${revision.note}` : ""}</p><button type="button" onClick={() => onRestore(revision)}>Draft로 복원</button></div>)}</section></> : null}
    </div></div>
    <AssetPicker open={pickerOpen} assets={content.assets} onClose={() => setPickerOpen(false)} onSelect={chooseAsset} onUpload={uploadAsset} onExternal={registerExternalAsset} />
  </section>;
}
