import type { AdminNavGroup, AdminWorkItem, AssetRecord } from "@/admin/types";

export const adminNavigation: AdminNavGroup[] = [
  {
    label: "Home",
    items: [
      { id: "home.hero", number: "01", label: "Hero" },
      { id: "home.about", number: "02", label: "About", previewAnchor: "about" },
      { id: "home.projects", number: "03", label: "Featured Projects", previewAnchor: "projects" },
      { id: "home.works", number: "04", label: "Selected Works", previewAnchor: "works" },
      { id: "home.career", number: "05", label: "Career", previewAnchor: "experience" },
      { id: "home.workflow", number: "06", label: "Workflow" },
      { id: "home.contact", number: "07", label: "Contact", previewAnchor: "contact" },
    ],
  },
  { label: "Works", items: [{ id: "works.archive", label: "Works Archive" }] },
  { label: "Projects", items: [{ id: "projects.index", label: "Project Entries" }] },
  { label: "Assets", items: [{ id: "assets.library", label: "Asset Library" }] },
  { label: "Settings", items: [{ id: "settings.site", label: "Site Settings" }] },
];

export const mockAssets: AssetRecord[] = [
  {
    id: "asset-about-studio",
    filename: "creative-workflow-studio.jpg",
    src: "/images/about/creative-workflow-studio.jpg",
    alt: "촬영 스튜디오에서 제품과 편집 화면을 확인하는 작업 장면",
    category: "Home",
    width: 1600,
    height: 1067,
    fileSize: "248 KB",
    uploadedAt: "2026.08.29",
    usageCount: 1,
    source: "library",
  },
  {
    id: "asset-livbee-main",
    filename: "main-desktop.png",
    src: "/images/livbee/main-desktop.png",
    alt: "LIVBEE 데스크톱 메인 화면",
    category: "LIVBEE",
    width: 1440,
    height: 900,
    fileSize: "492 KB",
    uploadedAt: "2026.08.29",
    usageCount: 2,
    source: "library",
  },
  {
    id: "asset-ocean",
    filename: "ocean-content-thumbnail.jpg",
    src: "/images/selected-works/ocean-content-thumbnail.jpg",
    alt: "바다 탐사 콘텐츠 유튜브 썸네일",
    category: "Works",
    width: 1280,
    height: 720,
    fileSize: "181 KB",
    uploadedAt: "2026.08.29",
    usageCount: 2,
    source: "library",
  },
  {
    id: "asset-live",
    filename: "live-commerce-studio.png",
    src: "/images/selected-works/live-commerce-studio.png",
    alt: "TV 제품 쇼핑라이브 현장 썸네일",
    category: "Shopping Live",
    width: 1280,
    height: 720,
    fileSize: "336 KB",
    uploadedAt: "2026.08.29",
    usageCount: 2,
    source: "library",
  },
];

export const mockWorks: AdminWorkItem[] = [
  {
    id: "ocean-content-thumbnail",
    title: "제주 바다를 지키는 어벤져스",
    category: "유튜브 썸네일",
    src: "/images/selected-works/ocean-content-thumbnail.jpg",
    exposure: "home-featured",
    published: true,
  },
  {
    id: "traffic-safety-thumbnail",
    title: "안전한가? - 철부지 우리 형",
    category: "유튜브 썸네일",
    src: "/images/selected-works/traffic-safety-motorcycle-thumbnail.jpg",
    exposure: "home",
    published: true,
  },
  {
    id: "shopping-live-studio",
    title: "10만대 판매기념 쇼핑라이브",
    category: "쇼핑라이브 콘텐츠",
    src: "/images/selected-works/live-commerce-studio.png",
    exposure: "home",
    published: true,
  },
  {
    id: "standards-event",
    title: "양자기술 4행시 이벤트",
    category: "이벤트 배너",
    src: "/images/selected-works/standards-event-four-line.jpg",
    exposure: "works-only",
    published: true,
  },
];
